### ISSUE TITLE
GTIN validation doesn't work

### ISSUE THREAD

**Issue by kkuciauskas** [bazaarvoice/tier3-sampling-automator#3] opened 2020-03-19 18:24 UTC
After editing one of the UPCs to have 14 digits instead of 12 and tool returns empty string instead of an error.
Original UPC: 681131349475 (valid)
Edited UPC: 68113134947523 (should be invalid)

Result:
`UPCs: '',`

**Comment by kkuciauskas** [comment] 2020-03-19 18:34
@vstaskevicius, please confirm the bug fix so I could merge the results to the master branch thereafter. Thank you.
https://github.com/bazaarvoice/tier3-sampling-automator/commit/38f69b1ae4cbc57bcba1fdc0240dee85239df4ca

**Comment by vstaskevicius** [comment] 2020-03-20 11:32
I cannot reproduce the issue, so I believe it's fixed now. Please merge it to master!

**Closed by vstaskevicius** 2020-03-20 11:32 UTC
Labels: bug
